# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZFgY4PB1HaaVzWBy-wNW0NCi4yN3C8Z
"""

# Install required libraries
!pip install -q ultralytics opencv-python-headless fer tensorflow deepface gtts pytesseract
!apt-get install -y tesseract-ocr

import cv2
import matplotlib.pyplot as plt
import numpy as np
from ultralytics import YOLO
from deepface import DeepFace
from gtts import gTTS
import os
import pytesseract
from google.colab.patches import cv2_imshow  # For Colab image display
from IPython.display import Audio, display  # For audio playback
import time

# Load YOLO model
def load_yolo_model(model_path='yolov8m.pt'):
    return YOLO(model_path)

# Object detection function
def detect_objects(model, img, conf_threshold=0.5, nms_threshold=0.4):
    results = model(img, conf=conf_threshold, iou=nms_threshold)
    return results

# Emotion detection function
def detect_emotions(img):
    try:
        analysis = DeepFace.analyze(img, actions=['emotion'], enforce_detection=False)
        return analysis[0]['dominant_emotion']
    except Exception as e:
        print(f"Emotion detection error: {e}")
        return None

# Text detection function
def detect_text(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    text = pytesseract.image_to_string(gray)
    return text.strip() if text.strip() else None  # Only return valid text

# Annotate image with bounding boxes, labels, and detected text
def annotate_image(img, results, conf_threshold=0.5):
    detected_objects = []

    # Object Detection
    for result in results:
        for box in result.boxes:
            conf = box.conf[0]
            if conf >= conf_threshold:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                label = result.names[int(box.cls[0])]
                detected_objects.append(label)
                cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(img, f'{label}: {conf:.2f}', (x1, y2 + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    # Emotion Detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(gray, 1.1, 5, minSize=(30, 30))

    for (x, y, w, h) in faces:
        face_img = img[y:y+h, x:x+w]
        emotion = detect_emotions(face_img)
        if emotion:
            detected_objects.append(f"Emotion: {emotion}")
            cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)
            cv2.putText(img, f'Emotion: {emotion}', (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    # Text Detection
    detected_text = detect_text(img)
    if detected_text:  # Only add to detected objects if valid text is found
        detected_objects.append(f"Text: {detected_text}")

    return img, detected_objects

# Play audio feedback
def play_audio_feedback(text):
    tts = gTTS(text=text, lang='en')
    tts.save("output.mp3")
    display(Audio("output.mp3", autoplay=True))

# Process full video with 2-second gap between detections
def process_video(video_path, model_path='yolov8m.pt', conf_threshold=0.5, nms_threshold=0.4, gap_seconds=2):
    model = load_yolo_model(model_path)
    cap = cv2.VideoCapture(video_path)

    # Ensure the video opened successfully
    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    fps = cap.get(cv2.CAP_PROP_FPS)  # Frames per second of the video
    frame_interval = int(fps * gap_seconds)  # Number of frames to skip based on gap_seconds

    print(f"Video FPS: {fps}, Frame interval: {frame_interval} frames for {gap_seconds} seconds.")

    last_detection_time = time.time()  # Track the last time something was detected

    frame_counter = 0
    detection_counter = 0  # To count detections based on the 2-second rule

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame_counter += 1

        # Only process every frame_interval frames
        if frame_counter % frame_interval == 0:
            results = detect_objects(model, frame, conf_threshold, nms_threshold)
            annotated_frame, detected_objects = annotate_image(frame, results, conf_threshold)

            # If detection exists
            if detected_objects:
                feedback = "Detected: " + ", ".join(detected_objects)
                print(f"Frame {frame_counter}: {feedback}")
                play_audio_feedback(feedback)
                detection_counter += 1

            # Show the processed frame
            cv2_imshow(annotated_frame)  # Use cv2_imshow for Colab compatibility

    print(f"\nTotal detections made: {detection_counter}")
    cap.release()

# 👉 TESTING VIDEO
video_path = 'vid.MOV'  # Change this to your uploaded video
process_video(video_path)

# Install required libraries
!pip install -q ultralytics opencv-python-headless fer tensorflow deepface gtts pytesseract
!apt-get install -y tesseract-ocr

import cv2
import matplotlib.pyplot as plt
import numpy as np
from ultralytics import YOLO
from deepface import DeepFace
from gtts import gTTS
import os
import pytesseract
from google.colab.patches import cv2_imshow  # For Colab image display
from IPython.display import Audio, display  # For audio playback
import time

# Load YOLO model
def load_yolo_model(model_path='yolov8m.pt'):
    return YOLO(model_path)

# Object detection function
def detect_objects(model, img, conf_threshold=0.5, nms_threshold=0.4):
    results = model(img, conf=conf_threshold, iou=nms_threshold)
    return results

# Emotion detection function
def detect_emotions(img):
    try:
        analysis = DeepFace.analyze(img, actions=['emotion'], enforce_detection=False)
        return analysis[0]['dominant_emotion']
    except Exception as e:
        print(f"Emotion detection error: {e}")
        return None

# Text detection function
def detect_text(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    text = pytesseract.image_to_string(gray)
    return text.strip() if text.strip() else None  # Only return valid text

# Annotate image with bounding boxes, labels, and detected text
def annotate_image(img, results, conf_threshold=0.5):
    detected_objects = []

    # Object Detection
    for result in results:
        for box in result.boxes:
            conf = box.conf[0]
            if conf >= conf_threshold:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                label = result.names[int(box.cls[0])]
                detected_objects.append(label)
                cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(img, f'{label}: {conf:.2f}', (x1, y2 + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    # Emotion Detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(gray, 1.1, 5, minSize=(30, 30))

    for (x, y, w, h) in faces:
        face_img = img[y:y+h, x:x+w]
        emotion = detect_emotions(face_img)
        if emotion:
            detected_objects.append(f"Emotion: {emotion}")
            cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)
            cv2.putText(img, f'Emotion: {emotion}', (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    # Text Detection
    detected_text = detect_text(img)
    if detected_text:
        detected_objects.append(f"Text: {detected_text}")

    return img, detected_objects

# Play audio feedback
def play_audio_feedback(text):
    tts = gTTS(text=text, lang='en')
    tts.save("output.mp3")
    display(Audio("output.mp3", autoplay=True))

# Process image input
def process_image(image_path, model_path='yolov8m.pt', conf_threshold=0.5):
    model = load_yolo_model(model_path)
    img = cv2.imread(image_path)
    results = detect_objects(model, img, conf_threshold)
    annotated_img, detected_objects = annotate_image(img, results, conf_threshold)

    # Show image
    cv2_imshow(annotated_img)

    # Audio feedback
    if detected_objects:
        feedback = "Detected: " + ", ".join(detected_objects)
        print(feedback)
        play_audio_feedback(feedback)
    else:
        print("No detections found.")

# Process video with 2-second gap
def process_video(video_path, model_path='yolov8m.pt', conf_threshold=0.5, nms_threshold=0.4, gap_seconds=2):
    model = load_yolo_model(model_path)
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_interval = int(fps * gap_seconds)
    print(f"Video FPS: {fps}, Frame interval: {frame_interval}")

    frame_counter = 0
    detection_counter = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame_counter += 1
        if frame_counter % frame_interval == 0:
            results = detect_objects(model, frame, conf_threshold, nms_threshold)
            annotated_frame, detected_objects = annotate_image(frame, results, conf_threshold)

            if detected_objects:
                feedback = "Detected: " + ", ".join(detected_objects)
                print(f"Frame {frame_counter}: {feedback}")
                play_audio_feedback(feedback)
                detection_counter += 1

            cv2_imshow(annotated_frame)

    print(f"\nTotal detections made: {detection_counter}")
    cap.release()


# 🖼️ To test with image
image_path = "h.jpg"  # 🔁 Change this to your uploaded image
process_image(image_path)

# 🎥 To test with video (2-sec gap)
video_path = "v.mp4"  # 🔁 Change this to your uploaded video
process_video(video_path)

# 📦 Install required libraries
!pip install -q ultralytics opencv-python-headless fer tensorflow deepface gtts pytesseract
!apt-get install -y tesseract-ocr

# 📚 Imports
import cv2
import numpy as np
from ultralytics import YOLO
from deepface import DeepFace
from gtts import gTTS
import pytesseract
from google.colab.patches import cv2_imshow
from IPython.display import Audio, display
import time

# 🎯 Load YOLO model
def load_yolo_model(model_path='yolov8m.pt'):
    return YOLO(model_path)

# 🧠 Object detection
def detect_objects(model, img, conf_threshold=0.5, nms_threshold=0.4):
    results = model(img, conf=conf_threshold, iou=nms_threshold)
    return results

# 😊 Emotion detection
def detect_emotions(img):
    try:
        analysis = DeepFace.analyze(img, actions=['emotion'], enforce_detection=False)
        return analysis[0]['dominant_emotion']
    except:
        return None

# 🔤 Text detection
def detect_text(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    text = pytesseract.image_to_string(gray)
    return text.strip() if text.strip() else None

# 🎤 Speak text
def speak(text):
    print(text)
    tts = gTTS(text=text, lang='en')
    tts.save("output.mp3")
    display(Audio("output.mp3", autoplay=True))
    time.sleep(2)

# 🧠 Main processing function
def annotate_and_speak_summary(img, results, conf_threshold=0.5):
    persons = []
    other_detections = []

    for result in results:
        for box in result.boxes:
            conf = box.conf[0]
            if conf >= conf_threshold:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                label = result.names[int(box.cls[0])]

                if label == "person":
                    persons.append((x1, y1, x2, y2))
                else:
                    other_detections.append(label)
                    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
                    cv2.putText(img, label, (x1, y2 + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    # 📣 Speak person count
    if persons:
        speak(f"Detected {len(persons)} persons.")
        for i, (x1, y1, x2, y2) in enumerate(persons):
            person_face = img[y1:y2, x1:x2]
            emotion = detect_emotions(person_face)
            label = f"Person {i+1}: {emotion if emotion else 'emotion not detected'}"
            speak(label)
            cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 0), 2)
            cv2.putText(img, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    # 🔡 Text
    text_found = detect_text(img)
    if text_found:
        speak(f"Detected text: {text_found}")

    return img

# 🖼️ Image process
def process_image(image_path, model_path='yolov8m.pt'):
    model = load_yolo_model(model_path)
    img = cv2.imread(image_path)
    results = detect_objects(model, img)
    annotated = annotate_and_speak_summary(img, results)
    cv2_imshow(annotated)

# 🎥 Video process with 2-sec interval
def process_video(video_path, model_path='yolov8m.pt', conf_threshold=0.5, nms_threshold=0.4, gap_seconds=2):
    model = load_yolo_model(model_path)
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_interval = int(fps * gap_seconds)
    print(f"Video FPS: {fps}, Frame interval: {frame_interval}")

    frame_counter = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame_counter += 1
        if frame_counter % frame_interval == 0:
            results = detect_objects(model, frame, conf_threshold, nms_threshold)
            annotated = annotate_and_speak_summary(frame, results, conf_threshold)
            cv2_imshow(annotated)

    cap.release()
    print("🎬 Video processing complete.")

# ✅ Run image
image_path = "h.jpg"  # your image path
process_image(image_path)

# ✅ Run video
video_path = "VID.MP4"  # your video path
process_video(video_path)

image_path = "k.jpg"  # 🔁 Change this to your uploaded image
process_image(image_path)

image_path = "download.jpg"  # 🔁 Change this to your uploaded image
process_image(image_path)

# 📦 Install required libraries
!pip install -q ultralytics opencv-python-headless fer tensorflow deepface gtts pytesseract
!apt-get install -y tesseract-ocr

# 📚 Imports
import cv2
import numpy as np
from ultralytics import YOLO
from deepface import DeepFace
from gtts import gTTS
import pytesseract
from google.colab.patches import cv2_imshow
from IPython.display import Audio, display
import time

# 🎯 Load YOLO model
def load_yolo_model(model_path='yolov8m.pt'):
    return YOLO(model_path)

# 🧠 Object detection
def detect_objects(model, img, conf_threshold=0.5, nms_threshold=0.4):
    results = model(img, conf=conf_threshold, iou=nms_threshold)
    return results

# 😊 Emotion detection
def detect_emotions(img):
    try:
        analysis = DeepFace.analyze(img, actions=['emotion'], enforce_detection=False)
        return analysis[0]['dominant_emotion']
    except:
        return None

# 🔤 Text detection
def detect_text(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    text = pytesseract.image_to_string(gray)
    return text.strip() if text.strip() else None

# 🎤 Speak text
def speak(text):
    print(text)
    tts = gTTS(text=text, lang='en')
    tts.save("output.mp3")
    display(Audio("output.mp3", autoplay=True))
    time.sleep(2)

# 🧠 Main processing function
def annotate_and_speak_summary(img, results, conf_threshold=0.5):
    persons = []
    other_detections = []

    for result in results:
        for box in result.boxes:
            conf = box.conf[0]
            if conf >= conf_threshold:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                label = result.names[int(box.cls[0])]

                if label == "person":
                    persons.append((x1, y1, x2, y2))
                else:
                    other_detections.append(label)
                    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
                    cv2.putText(img, label, (x1, y2 + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    # 📣 Speak person count
    if persons:
        speak(f"Detected {len(persons)} persons.")
        for i, (x1, y1, x2, y2) in enumerate(persons):
            person_face = img[y1:y2, x1:x2]
            emotion = detect_emotions(person_face)
            label = f"Person {i+1}: {emotion if emotion else 'emotion not detected'}"
            speak(label)
            cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 0), 2)
            cv2.putText(img, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    # 🔡 Text
    text_found = detect_text(img)
    if text_found:
        speak(f"Detected text: {text_found}")

    return img

# 🖼️ Image process
def process_image(image_path, model_path='yolov8m.pt'):
    model = load_yolo_model(model_path)
    img = cv2.imread(image_path)
    results = detect_objects(model, img)
    annotated = annotate_and_speak_summary(img, results)
    cv2_imshow(annotated)

# 🎥 Video process with 2-sec interval
def process_video(video_path, model_path='yolov8m.pt', conf_threshold=0.5, nms_threshold=0.4, gap_seconds=2):
    model = load_yolo_model(model_path)
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("Error: Could not open video.")
        return

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_interval = int(fps * gap_seconds)
    print(f"Video FPS: {fps}, Frame interval: {frame_interval}")

    frame_counter = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame_counter += 1
        if frame_counter % frame_interval == 0:
            results = detect_objects(model, frame, conf_threshold, nms_threshold)
            annotated = annotate_and_speak_summary(frame, results, conf_threshold)
            cv2_imshow(annotated)

    cap.release()
    print("🎬 Video processing complete.")

# ✅ Run image
image_path = "h.jpg"  # your image path
process_image(image_path)

# ✅ Run video
video_path = "vid.MOV"  # your video path
process_video(video_path)

video_path = "VID.MOV"  # your video path
process_video(video_path)